version: '2.2'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres -d sample"
      interval: 20s
      timeout: 20s
      retries: 5
