version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U postgres -d sample"
      interval: 20s
      timeout: 20s
      retries: 5
  token_storage:
    depends_on:
      - db
    image: redis:6.2.4-alpine
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    command: --requirepass redis
